[project]
name = "pmpp"
version = "0.1.0"
description = "Programming Massively Parallel Processors examples"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.9.1",
    "numpy",
    "ninja",
]

[tool.uv.workspace]
members = ["timing", "06-matmul", "07-convolution"]

